"""Template generation for Ralphy PRD, prompts, and config files."""

from ralphy.constants import (
    CB_INACTIVITY_TIMEOUT_SECONDS,
    CB_MAX_ATTEMPTS,
    CB_MAX_OUTPUT_SIZE_BYTES,
    CB_MAX_REPEATED_ERRORS,
    CB_TASK_STAGNATION_TIMEOUT_SECONDS,
    DEFAULT_RETRY_ATTEMPTS,
    DEFAULT_RETRY_DELAY_SECONDS,
    IMPL_TIMEOUT_SECONDS,
    PR_TIMEOUT_SECONDS,
    QA_TIMEOUT_SECONDS,
    SPEC_TIMEOUT_SECONDS,
    AGENT_TIMEOUT_SECONDS,
)


def generate_quick_prd(description: str) -> str:
    """Generate minimal PRD.md content from a description.

    Args:
        description: The feature description

    Returns:
        PRD markdown content
    """
    return f"""# {description.strip()}

## Objective

{description.strip()}

## Requirements

Implement the feature as described above.

---
*Generated by Ralphy Quick Start mode*
"""


# List of prompt files to copy
PROMPT_FILES = [
    "spec_agent.md",
    "dev_prompt.md",
    "qa_agent.md",
    "pr_agent.md",
]


def generate_prompt_header(prompt_file: str) -> str:
    """Generates a header documenting available placeholders for a prompt.

    Args:
        prompt_file: Prompt file name (e.g., spec_agent.md)

    Returns:
        Markdown header with placeholder documentation.
    """
    # Placeholders common to all prompts
    common_placeholders = """
| Placeholder | Description |
|-------------|-------------|
| `{{project_name}}` | Project name |
| `{{language}}` | Tech stack (from config.yaml) |
| `{{test_command}}` | Test command (from config.yaml) |
"""

    # Agent-specific placeholders
    specific_placeholders = {
        "spec_agent.md": """| `{{prd_content}}` | Content of PRD.md |
""",
        "dev_prompt.md": """| `{{spec_content}}` | Content of SPEC.md |
| `{{tasks_content}}` | Content of TASKS.md |
| `{{resume_instruction}}` | Resume instructions (empty if new session) |
| `{{orchestration_section}}` | Agent orchestration instructions (if agents exist) |
""",
        "qa_agent.md": """| `{{spec_content}}` | Content of SPEC.md |
""",
        "pr_agent.md": """| `{{branch_name}}` | Branch name to create |
| `{{qa_report}}` | QA report content |
| `{{spec_content}}` | Content of SPEC.md |
""",
    }

    # Extract agent name from filename
    agent_name = prompt_file.replace("_agent.md", "").replace("_prompt.md", "").replace("_", " ").title()
    specific = specific_placeholders.get(prompt_file, "")

    return f"""<!--
=============================================================================
CUSTOM PROMPT TEMPLATE - {agent_name} Agent
=============================================================================

This file is a custom prompt template for Ralphy.
Modify it to adapt agent behavior to your stack/project.

IMPORTANT: This prompt MUST contain the "EXIT_SIGNAL" instruction so
the agent can signal the end of its execution.

Available placeholders (replaced automatically at runtime):
{common_placeholders}{specific}
Documentation: https://github.com/your-org/ralphy#custom-prompts
=============================================================================
-->

"""


def generate_config_template() -> str:
    """Generate config.yaml template with default values and documentation.

    Returns:
        A YAML string with all config sections, default values, and comments.
    """
    return f"""# =============================================================================
# RALPHY CONFIGURATION
# =============================================================================
# This file configures Ralphy's behavior for this project.
# All values shown are defaults. Only override what you need to change.
#
# Documentation: https://github.com/ThibautBaissac/Ralphy#configuration
# =============================================================================

# -----------------------------------------------------------------------------
# Project Settings
# -----------------------------------------------------------------------------
project:
  name: my-project  # Project name used in agent prompts

# -----------------------------------------------------------------------------
# Model Configuration
# -----------------------------------------------------------------------------
# Claude model to use for each phase. Options: sonnet, opus, haiku
# or full model names like claude-sonnet-4-5-20250929
models:
  specification: sonnet  # Spec generation (balanced)
  implementation: sonnet  # Code implementation (most capable recommended)
  qa: sonnet             # Quality analysis (balanced)
  pr: sonnet             # PR creation (fast is fine)

# -----------------------------------------------------------------------------
# Tech Stack
# -----------------------------------------------------------------------------
stack:
  language: typescript     # Primary language/framework
  test_command: npm test   # Command to run tests
  tdd_enabled: true        # Enable TDD mode (run tests after each task)

# -----------------------------------------------------------------------------
# Timeouts (seconds)
# -----------------------------------------------------------------------------
timeouts:
  specification: {SPEC_TIMEOUT_SECONDS}   # 30 min - Spec generation
  implementation: {IMPL_TIMEOUT_SECONDS}  # 4h - Code implementation
  qa: {QA_TIMEOUT_SECONDS}              # 30 min - QA analysis
  pr: {PR_TIMEOUT_SECONDS}               # 10 min - PR creation
  agent: {AGENT_TIMEOUT_SECONDS}              # 5 min - Fallback timeout

# -----------------------------------------------------------------------------
# Retry Configuration
# -----------------------------------------------------------------------------
retry:
  max_attempts: {DEFAULT_RETRY_ATTEMPTS}       # Total attempts (1 = no retry)
  delay_seconds: {DEFAULT_RETRY_DELAY_SECONDS}      # Delay between retries

# -----------------------------------------------------------------------------
# Circuit Breaker - Protection against infinite loops
# -----------------------------------------------------------------------------
circuit_breaker:
  enabled: true
  inactivity_timeout: {CB_INACTIVITY_TIMEOUT_SECONDS}     # Seconds without output before warning
  max_repeated_errors: {CB_MAX_REPEATED_ERRORS}      # Same error count before warning
  task_stagnation_timeout: {CB_TASK_STAGNATION_TIMEOUT_SECONDS}  # Seconds without task completion (dev-agent)
  max_output_size: {CB_MAX_OUTPUT_SIZE_BYTES}    # Max cumulative output in bytes (500KB)
  max_attempts: {CB_MAX_ATTEMPTS}            # Warnings before circuit trips
"""
