"""Template generation for Ralphy PRD, agents, and config files."""

from ralphy.constants import (
    CB_INACTIVITY_TIMEOUT_SECONDS,
    CB_MAX_ATTEMPTS,
    CB_MAX_OUTPUT_SIZE_BYTES,
    CB_MAX_REPEATED_ERRORS,
    CB_TASK_STAGNATION_TIMEOUT_SECONDS,
    DEFAULT_RETRY_ATTEMPTS,
    DEFAULT_RETRY_DELAY_SECONDS,
    IMPL_TIMEOUT_SECONDS,
    PR_TIMEOUT_SECONDS,
    QA_TIMEOUT_SECONDS,
    SPEC_TIMEOUT_SECONDS,
    AGENT_TIMEOUT_SECONDS,
)


def generate_quick_prd(description: str) -> str:
    """Generate minimal PRD.md content from a description.

    Args:
        description: The feature description

    Returns:
        PRD markdown content
    """
    return f"""# {description.strip()}

## Objective

{description.strip()}

## Requirements

Implement the feature as described above.

---
*Generated by Ralphy Quick Start mode*
"""


# List of agent files to copy
AGENT_FILES = [
    "spec-agent.md",
    "dev-agent.md",
    "qa-agent.md",
    "pr-agent.md",
]


def generate_config_template() -> str:
    """Generate config.yaml template with default values and documentation.

    Returns:
        A YAML string with all config sections, default values, and comments.
    """
    return f"""# =============================================================================
# RALPHY CONFIGURATION
# =============================================================================
# This file configures Ralphy's behavior for this project.
# All values shown are defaults. Only override what you need to change.
#
# Documentation: https://github.com/ThibautBaissac/Ralphy#configuration
# =============================================================================

# -----------------------------------------------------------------------------
# Project Settings
# -----------------------------------------------------------------------------
project:
  name: my-project  # Project name used in agent prompts

# -----------------------------------------------------------------------------
# Model Configuration
# -----------------------------------------------------------------------------
# Claude model to use for each phase. Options: sonnet, opus, haiku
# or full model names like claude-sonnet-4-5-20250929
models:
  specification: sonnet  # Spec generation (balanced)
  implementation: sonnet  # Code implementation (most capable recommended)
  qa: sonnet             # Quality analysis (balanced)
  pr: sonnet             # PR creation (fast is fine)

# -----------------------------------------------------------------------------
# Tech Stack
# -----------------------------------------------------------------------------
stack:
  language: typescript     # Primary language/framework
  test_command: npm test   # Command to run tests
  tdd_enabled: true        # Enable TDD mode (run tests after each task)

# -----------------------------------------------------------------------------
# Timeouts (seconds)
# -----------------------------------------------------------------------------
timeouts:
  specification: {SPEC_TIMEOUT_SECONDS}   # 30 min - Spec generation
  implementation: {IMPL_TIMEOUT_SECONDS}  # 4h - Code implementation
  qa: {QA_TIMEOUT_SECONDS}              # 30 min - QA analysis
  pr: {PR_TIMEOUT_SECONDS}               # 10 min - PR creation
  agent: {AGENT_TIMEOUT_SECONDS}              # 5 min - Fallback timeout

# -----------------------------------------------------------------------------
# Retry Configuration
# -----------------------------------------------------------------------------
retry:
  max_attempts: {DEFAULT_RETRY_ATTEMPTS}       # Total attempts (1 = no retry)
  delay_seconds: {DEFAULT_RETRY_DELAY_SECONDS}      # Delay between retries

# -----------------------------------------------------------------------------
# Circuit Breaker - Protection against infinite loops
# -----------------------------------------------------------------------------
circuit_breaker:
  enabled: true
  inactivity_timeout: {CB_INACTIVITY_TIMEOUT_SECONDS}     # Seconds without output before warning
  max_repeated_errors: {CB_MAX_REPEATED_ERRORS}      # Same error count before warning
  task_stagnation_timeout: {CB_TASK_STAGNATION_TIMEOUT_SECONDS}  # Seconds without task completion (dev-agent)
  max_output_size: {CB_MAX_OUTPUT_SIZE_BYTES}    # Max cumulative output in bytes (500KB)
  max_attempts: {CB_MAX_ATTEMPTS}            # Warnings before circuit trips
"""
